# ===================================================================== #
# BASIC CONFIGURATION
# ===================================================================== #

# Arch: "default", "x86_64", "aarch64".
# "default" corresponds to the host architecture.
arch: "default"

# An image must support systemd and cloud-init.
# Ubuntu and Fedora are known to work.
# Default: none (must be specified)
images:
  - location: "~/Projects/GitHub/autoscaled-masterkube-multipass/images/jammy-kubernetes-k3s-v1.29.0+k3s1-arm64.img"
    arch: "aarch64"

# CPUs: if you see performance issues, try limiting cpus to 1.
# Default: 4
# TODO: change the memory
cpus: 2

# Memory size
# TODO: change the memory
memory: "2GiB"

# Disk size
# TODO: change the storage size
disk: "20GiB"
