kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cinder-csi-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: cinder.csi.openstack.org
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: "xfs" #Optional Parameter